# Generated by Django 3.1 on 2020-09-10 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=50)),
                ('category1', models.CharField(max_length=50)),
                ('category2', models.CharField(blank=True, max_length=50)),
                ('category3', models.CharField(blank=True, max_length=50)),
                ('category4', models.CharField(blank=True, max_length=50)),
                ('category5', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(unique=True)),
                ('github', models.URLField()),
                ('linedin', models.URLField()),
                ('desc', models.TextField()),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='hireus/images')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
