# Generated by Django 3.1 on 2020-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('mob', models.CharField(max_length=12)),
                ('Product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('desc', models.TextField()),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='hireus/images')),
            ],
        ),
    ]
