# Generated by Django 3.1.1 on 2020-09-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imagecourse',
            field=models.ImageField(default=0, upload_to='course/images/course'),
            preserve_default=False,
        ),
    ]
