# Generated by Django 3.1.1 on 2020-09-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subject_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='author',
        ),
    ]
