# Generated by Django 3.1.1 on 2020-09-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=255)),
                ('mob', models.CharField(max_length=12)),
                ('comment', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='gem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
                ('desc', models.TextField()),
                ('special', models.TextField()),
                ('image', models.ImageField(default='', upload_to='home/images/gems/')),
            ],
        ),
    ]
