# Generated by Django 3.1 on 2020-08-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
    ]
